using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class Bant : MonoBehaviour
{
    [SerializeField] Renderer _Renderer;// Inspectorï¿½da dï¿½zenlenebilir hale getirir.
    float BantHizi= .3f;
    // Update is called once per frame
    void Update()
    {
        if (Time.deltaTime != 0)
        //Bandï¿½n hareketini saï¿½ladï¿½m burada
            _Renderer.material.SetTextureOffset("_BaseMap", new Vector2(0, -Time.time * BantHizi));
        }
    private void OnTriggerStay(Collider other)
    {
        if (Time.timeScale != 0)
            //ï¿½zerinden bulunan tï¿½m objelere gï¿½ï¿½ uygulamasï¿½ iï¿½in
            other.transform.Translate((BantHizi-(BantHizi/3))*Time.deltaTime*Vector3.right,Space.World);
    }
}
